/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
